package br.com.offer.core.domain.entities

import br.com.offer.core.domain.enums.OfferStatusEnum
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum
import java.util.Date

@DynamoDBTable(tableName = "offer")
data class Offer(

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var offerID: String? = null,

    @DynamoDBAttribute
    var storeID: String? = null,

    @DynamoDBAttribute
    var createdAt: Date = Date(),

    @DynamoDBAttribute
    var description: String? = null,

    @DynamoDBAttribute
    var slug: String? = null,

    @DynamoDBAttribute
    var price: Double = 0.0,

    @DynamoDBAttribute
    var lastPrice: Double = 0.0,

    @DynamoDBAttribute
    var tag: String? = null,

    @DynamoDBAttribute
    var image: String? = null,

    @DynamoDBAttribute
    var metrics: OfferMetrics? = null,

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    var status: OfferStatusEnum = OfferStatusEnum.PENDING
)