version: '3.9'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - offer-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - offer-network

  offer-core:
    container_name: offer-core
    image: offer/offer-core
    build: ./offer-core
    working_dir: /offer-core
    restart: always
    command: ./mvnw spring-boot:run
    ports:
      - "8080:80"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SQS_ENDPOINT=${AWS_SQS_ENDPOINT}
      - AWS_SNS_EVENTS_OFFER_TOPIC=events-offer-topic
      - TZ=America/Sao_Paulo
    networks:
      - offer-network

  offer-search:
    container_name: offer-search
    image: offer/offer-search
    build: ./offer-search
    working_dir: /offer-search
    restart: always
    command: ./mvnw spring-boot:run
    ports:
      - "8100:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SQS_ENDPOINT=${AWS_SQS_ENDPOINT}
      - AWS_SNS_EVENTS_OFFER_TOPIC=events-offer-topic
      - ELASTICSEARCH_ENDPOINT=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=offer-search
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_DEV=true
      - TZ=America/Sao_Paulo
    depends_on:
      - elasticsearch
    networks:
      - offer-network

networks:
  offer-network:
      name: offer-network
      driver: bridge

volumes:
  esdata:
    driver: local