server:
  port: 80
cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-1}
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY:empty}
      secret-key: ${AWS_SECRET_KEY:empty}
    sqs:
      endpoint: ${AWS_SQS_ENDPOINT:empty}
sns:
  topics:
    events-offer: ${AWS_SNS_EVENTS_OFFER_TOPIC:empty}
springdoc:
  default-produces-media-type: application/json
