version: '3.9'

services:

  offer-core:
    container_name: offer-core
    image: 733419978185.dkr.ecr.us-east-1.amazonaws.com/offer-core:latest
    working_dir: /
    restart: always
    command: ./mvnw spring-boot:run
    ports:
      - "8080:80"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SQS_ENDPOINT=${AWS_SQS_ENDPOINT}
      - AWS_SNS_EVENTS_OFFER_TOPIC=events-offer-topic
      - TZ=America/Sao_Paulo
    networks:
      - offer-network

  offer-search:
    container_name: offer-search
    image: 733419978185.dkr.ecr.us-east-1.amazonaws.com/offer-search:latest
    working_dir: /
    restart: always
    command: ./mvnw spring-boot:run
    ports:
      - "8100:80"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SQS_ENDPOINT=${AWS_SQS_ENDPOINT}
      - AWS_SNS_EVENTS_OFFER_TOPIC=events-offer-topic
      - ELASTICSEARCH_ENDPOINT=${ELASTICSEARCH_ENDPOINT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_DEV=true
      - TZ=America/Sao_Paulo
    depends_on:
      - elasticsearch
    networks:
      - offer-network

networks:
  offer-network:
      name: offer-network
      driver: bridge