version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2022!
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2022!
    ports:
      - "27017:27017"
    volumes:
      - /Users/nrsjnet/Dev/Estudos/PosGraduacao/projeto-final/offer-backend/.Docker/volumes/MongoDB:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge